#include <mpi.h>
#include <iostream>
#include <cstdlib>
#include <ctime>
#include <cmath>

int main(int argc, char *argv[]) {
    int rank, size, i; // N, P, seed;
    long long n, local_n, count = 0, total_count; // sampleSize;
    double x, y, distance, pi_estimate, start_time, end_time; // integral, total;

    MPI_Init(&argc, &argv); // Initialize MPI
    MPI_Comm_rank(MPI_COMM_WORLD, &rank); // Get the rank of the current process
    MPI_Comm_size(MPI_COMM_WORLD, &size); // Get the total number of processes

    // Parsing command line arguments
    if (rank == 0) {
        if (argc != 2) {
            std::cout << "Invalid number of argumemnts." << std::endl;
            MPI_Abort(MPI_COMM_WORLD, 1);
        }
        n = atoll(argv[1]);
        start_time = MPI_Wtime();
    }

    // Broadcast n to all processes
    MPI_Bcast(&n, 1, MPI_LONG_LONG, 0, MPI_COMM_WORLD);

    // Each process now has a different random seed
    srand(time(NULL) + rank);

    // Calculate the number of points to be generated by each process
    local_n = n / size;

    // Generate points and count the number of points that fall within the circle
    for (i = 0; i < local_n; i++) {
        x = static_cast<double>(rand()) / RAND_MAX;
        y = static_cast<double>(rand()) / RAND_MAX;
        distance = sqrt(x * x + y * y);

        if (distance <= 1.0) {
            count++;
        }
    }

    // Reduce the count of each process to the total count
    MPI_Reduce(&count, &total_count, 1, MPI_LONG_LONG, MPI_SUM, 0, MPI_COMM_WORLD);

    // Calculate the value of pi and print it
    if (rank == 0) {
        pi_estimate = 4.0 * total_count / n;
        end_time = MPI_Wtime();
        std::cout.precision(12);
        std::cout << std::fixed << pi_estimate << ", " << end_time - start_time << std::endl;
    }

    // Finalize MPI
    MPI_Finalize();
    return 0;
}

