#include <mpi.h>
#include <iostream>
#include <cstdlib>
#include <ctime>
#include <cmath>

int main(int argc, char *argv[]) {
    int rank, size; // Rank and size of the current process
    int n; // Number of points
    double x, y, pi_estimate, start_time, end_time; // Random points, estimated value of pi, start and end time

    MPI_Init(&argc, &argv); // Initialize MPI
    MPI_Comm_rank(MPI_COMM_WORLD, &rank); // Get the rank of the current process
    MPI_Comm_size(MPI_COMM_WORLD, &size); // Get the total number of processes

    // Parsing command line arguments
    if (rank == 0) {
        if (argc != 2) {
            std::cout << "Invalid number of argumemnts." << std::endl;
            MPI_Abort(MPI_COMM_WORLD, 1);
        }
        n = atoi(argv[1]);
        start_time = MPI_Wtime();
    }

    // Broadcast n to all processes
    MPI_Bcast(&n, 1, MPI_INT, 0, MPI_COMM_WORLD);

    // Each process now has a different random seed
    srand(time(NULL) + rank);

    // Calculate the number of points to be generated by each process
    int local_n = n / size;

    // Generate points and count the number of points that fall within the circle
    int count = 0;
    for (int i = 0; i < local_n; i++) {
        x = double(rand()) / RAND_MAX;
        y = double(rand()) / RAND_MAX;

        if (pow(x, 2) + pow(y, 2) <= 1.0) {
            count++;
        }
    }

    // Reduce the count of each process to the total count
    int total_count;
    MPI_Reduce(&count, &total_count, 1, MPI_INT, MPI_SUM, 0, MPI_COMM_WORLD);

    // Calculate the value of pi and print it
    if (rank == 0) {
        pi_estimate = 4.0 * total_count / n;
        end_time = MPI_Wtime();
        std::cout.precision(12);
        std::cout << std::fixed << pi_estimate << ", " << end_time - start_time << std::endl;
    }

    // Finalize MPI
    MPI_Finalize();
    return 0;
}

